### ISSUE TITLE
CompilerResult.hasCompileErrors() - name does not match the purpose of the method

### ISSUE THREAD

**Issue by eltur100** [bendisposto/virtual-kata-lib#2]
> `boolean hasCompileErrors()`
> Returns:
> true, if and only if the compilation process produced no error messages

The statement mentioned above is stated in JavaDoc. However, the naming convention is not correct for this method. Either way, it should return false if there are no errors, or the method name should be changed into hasNoCompileErrors().

**Comment by bendisposto** [comment]
Yes, this is a very bad name. However, because changing it will break all clients. I will not change the name. I will add some explanation to the Javadoc.

**Comment by dasKeks** [comment]
Why not add a second method with the name 'hasNoCompileErrors()' and the exact same behavior and mark the method hasCompileErrors() as deprecated with a reference to the new method?

**Comment by bendisposto** [comment]
I considered that solution but I think this might lead to even more confusion, because there are thow methods with contradicting names that do exactly the same

I will probably change the method name in version 2.0, but for now I think it ist best to keep it as it is

**Comment by dasKeks** [comment]
I just took another look and it looks like only the javadoc "Returns: true, if and only if the compilation process produced no error messages" ist wrong.

The method name actually matches its behavior.

**Comment by bendisposto** [comment]
Rule 1: Trust the code, not the doc ;-) 
Thanks! I fixed the docs
